# Project
version=4.3.2
group=net.typho

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod.id=vibrancy
mod.name=Vibrancy
mod.author=The Typhothanian
mod.description=A Minecraft visuals mod that adds dynamic lights/shadows from blocks, items, and the sun
mod.credits=
mod.license=MIT

deps.minecraft=[VERSIONED]
deps.fabric-loader=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]